title: pearls
owner: pearl
email:
description: Pearls Minimal Project Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://e-s-l.github.io/" # the base hostname & protocol for your site
language: en
twitter_username:
github_username: e-s-l
disqus_username: 

# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: expanded   # compressed
